name: Github CI

on: [push, pull_request]

env:
  MAVEN_OPTS: -Dmaven.artifact.threads=256 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

jobs:
  build:
    name: Package RendezVous
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.18.0
        with:
          maven-version: 3.6.3
          java-version: '21'
          java-distribution: 'zulu'
          cache-enabled: 'true'
          cache-path: '~/.m2/repository'
          cache-prefix: 'citelibre'
      - name: Build
        run: mvn package -Passembly,rendezvous
